-- View first 10 rows
SELECT * 
FROM custo
LIMIT 10;

-- Q1. What is the total revenue generated by male vs. female customers?
SELECT 
    gender, 
    SUM(purchase_amount) AS total_revenue
FROM custo
GROUP BY gender;

-- Q2. Which customers used a discount but still spent more than the average purchase amount?
SELECT 
    customer_id, 
    purchase_amount
FROM custo
WHERE discount_applied = 'Yes'
AND purchase_amount > (
    SELECT AVG(purchase_amount) FROM custo
);

-- Q3. Which are the top 5 products with the highest average review rating?
SELECT 
    item_purchased,
    ROUND(AVG(review_rating::numeric), 2) AS average_rating
FROM custo
GROUP BY item_purchased
ORDER BY average_rating DESC
LIMIT 5;

-- Q4. Compare the average Purchase Amounts between Standard and Express Shipping.
SELECT 
    shipping_type,
    AVG(purchase_amount) AS avg_purchase
FROM custo
WHERE shipping_type IN ('Express', 'Standard')
GROUP BY shipping_type;

-- Q5. Do subscribed customers spend more?
SELECT 
    subscription_status,
    ROUND(AVG(purchase_amount), 2) AS avg_spend,
    ROUND(SUM(purchase_amount), 2) AS total_revenue,
    COUNT(customer_id) AS total_customers
FROM custo
GROUP BY subscription_status
ORDER BY total_revenue DESC;

-- Q6. Which products have the highest percentage of purchases with discounts applied?
SELECT 
    item_purchased,
    ROUND(
        100.0 * SUM(CASE WHEN discount_applied = 'Yes' THEN 1 ELSE 0 END) 
        / COUNT(*), 2
    ) AS discount_percentage
FROM custo
WHERE item_purchased LIKE 'S%'
GROUP BY item_purchased
ORDER BY discount_percentage DESC;

-- Q7. Segment customers into New, Returning, and Loyal
SELECT 
    CASE 
        WHEN previous_purchases = 0 THEN 'New'
        WHEN previous_purchases BETWEEN 1 AND 5 THEN 'Returning'
        ELSE 'Loyal'
    END AS customer_segment,
    COUNT(*) AS total_customers
FROM custo
GROUP BY customer_segment;

-- Q8. What are the top 3 most purchased products within each category?
SELECT *
FROM (
    SELECT 
        category,
        item_purchased,
        COUNT(*) AS total_orders,
        RANK() OVER (PARTITION BY category ORDER BY COUNT(*) DESC) AS rank
    FROM custo
    GROUP BY category, item_purchased
) t
WHERE rank <= 3;

-- Q9. Are repeat buyers (more than 5 previous purchases) likely to subscribe?
SELECT 
    subscription_status,
    COUNT(*) AS repeat_customers
FROM custo
WHERE previous_purchases > 5
GROUP BY subscription_status;

-- Q10. What is the revenue contribution of each age group?
SELECT 
    age_group,
    SUM(purchase_amount) AS revenue
FROM custo
GROUP BY age_group;